### ISSUE TITLE
[argoconfig] ability to create namespaces

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/helm-charts#115]
**Is your feature request related to a problem? Please describe.**
There is no way to manage namespaces as of now.

**Describe the solution you'd like**
I thought about having argoconfig create namespaces according to the applications' `destination.namespace` 

**Describe alternatives you've considered**
creating a standalone chart for namespace creation

**Affected chart**
`infra-apps`

**Additional context**
A.e. the application `velero` in `infra-apps` sets it's `destination.namespace` to `infra-velero`. `Argoconfig` could make sure the namespace is also created.

**Comment by hairmare** [comment]
Namespace autocreation is in Argo CD's scope and will be available with >1.7.8 (https://github.com/argoproj/argo-cd/pull/3976)

We will need to configure it in `syncPolicy` which is already supported by the `argoconfig` library.

```
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```

I'm not sure if we can set some global default syncOptions to enable this everywhere if we decide to go down that route.

Given that we are considering to use namespaces as a security boundary i'm not all that sure if I'd not rather manage namespaces somewhere else (ie. together with rbac and other security things).

**Comment by konokimo** [comment]
I think this feature is great. One thing is Namespace annotations, for istio-injection for example. That is where I see this feature getting to be a bunch of work or not as useful as it seems to be.

**Comment by eyenx** [comment]
How would we manage setting labels on namespaces then for being able of using rbac-manager correctly? Isn't this then ending up with having a own `infra-apps/namespaces` application?

**Comment by eyenx** [comment]
Also, how are we handling AppProject creation when bootstrapping a new cluster? Is this done manually?

**Comment by tongpu** [comment]
> Also, how are we handling AppProject creation when bootstrapping a new cluster? Is this done manually?

Initial creation of the first AppProject might need to be manual (like deploying ArgoCD with the Helm chart) and then we can probably use the raw YAML approach we're using for `*-apps`.
