### ISSUE TITLE
timed: Run migrations before spinning up updated pods

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/helm-charts#12]
The Django migrations should run before the new backend pods are spun up.

I think it would make sense to move `timed-chart/charts/timed/templates/job-dbmigrate.yaml` to a `pre-install` hook to ensure it runs at the right time in the lifecycle.

Most likely Helm hooks did not exist when this chart was originally created.

**Comment by tongpu** [comment]
Is there an automated way in Django to handle a rollback of migrations?

**Comment by hairmare** [comment]
> Is there an automated way in Django to handle a rollback of migrations?

You can rollback migrations by specifying what migration you would like to go back to: https://docs.djangoproject.com/en/3.0/topics/migrations/#reversing-migrations

We need to keep in mind that there might also be irreversible migrations (ie. a migration that removes data can't be rollbacked).

A lot of making rollbacking possible or better yet obsolete boils down to ensuring plus one minus one version compatibility when doing schema changes.

**Comment by kingdonb** [comment]
I logged into my "web" pod and found that I could run `sentry upgrade` manually, which seems to be the way to trigger migrations. I got errors in pods that depend on some of those migrations, but if I was meant to do this manually, I don't see how it can be discovered by an ordinary user. (Fortunately I think I'm above average persistent)

It actually looks like things are working now! 🎉

I could not find this step documented anywhere, but from reading over this issue I got the impression that it should have happened at helm install time. Again I'm new here and not sure how or why it didn't. I think I've followed all of the examples and I am not sure how this is supposed to happen. Does argocd actually trigger hooks when it does its helm tasks?

**Comment by kingdonb** [comment]
After further inspection I can see that a few kafka topics also failed to create, leaving `sentry-snuba-replacer-688769ff6c-jrm6m`, `sentry-snuba-outcomes-consumer-666ff5d688-6p9xq`, and `sentry-sessions-consumer-66c655cd-cqvr9` in crashloop backoff state. (Any hint how I can cajole these kafka topics into being created? running `sentry upgrade` a second time had no effect)

**Comment by kingdonb** [comment]
... ok, not quite. Further digging indicates that `snuba migrate` also never ran successfully, so I am also missing `default.sentry_dist` table ? and it does not have a `--force` option. Also getting internal certificate verification errors owing to perhaps the fact that I used the SelfSigned issuer as described in the examples. Not sure how to work around...

It seems like many of these issues might be avoided if I install https://github.com/sentry-kubernetes/charts directly with helm3 rather than through the argocd app lifecycle. I'm going to try that, but as I am using argocd and it looks like this "sentry-apps" repo is actively maintained, I'm interested to try again later!

**Comment by tongpu** [comment]
@kingdonb This issue is about Django migrations in the timed Helm chart. Your issues seem to be with the sentry chart that is part of `sentry-apps`. Would you please open a new issue for that and then we can figure out if it's related to ArgoCD or an issue with the upstream chart.

**Comment by kingdonb** [comment]
You're absolutely right, I did not understand the meaning of `timed` in the title

See #143
