### ISSUE TITLE
[rbac-definitions] No RBAC Definition App for RBAC Manager

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/helm-charts#131]
**Is your feature request related to a problem? Please describe.**
We are deploying rbac-manager with infra-apps here: https://github.com/adfinis-sygroup/helm-charts/blob/master/charts/infra-apps/values.yaml#L83

But ther is no app managing the definitions. We should have an app defining the rbac definitions as follows:

https://github.com/FairwindsOps/rbac-manager/blob/master/examples/rbacdefinition-sa-imagepull.yaml

**Describe the solution you'd like**
Additional rbac-definition app inside infra-apps

**Describe alternatives you've considered**
Managing rbac-definitions directly with rbac-manager app, but there is no way of doing this with upstream rbac-manager chart:
https://github.com/FairwindsOps/charts/blob/master/stable/rbac-manager/values.yaml

**Affected chart**
`infra-apps/rbac-manager`

**Additional context**
--

**Comment by eyenx** [comment]
For the moment managed as RAW YAML

**Comment by hairmare** [comment]
As per the docs the `-apps` charts are just a collection of the (chart_repo, chart_name, chart_version) tuple.

As such, for the proposed solution, there would need to be a chart available to add to `infra-apps` as part of this issue. I didn't look very far, but i don't think such a chart currently exists.

As for the considered alternative, did upstream every decline adding the resources to their chart in a vein similar to other `-stack` style charts?

**Comment by eyenx** [comment]
I created an issue https://github.com/adfinis-sygroup/helm-charts/issues/131

**Comment by eyenx** [comment]
> As for the considered alternative, did upstream every decline adding the resources to their chart in a vein similar to other `-stack` style charts?

Yes, Upstream declined today the implementation. Even referenced cert-manager where we also have a custom Chart for issuers. 

I'll go ahead and create a new chart then.

**Comment by eyenx** [comment]
#581
