### ISSUE TITLE
sentry-apps: relay does not become healthy, hooks do not run on sentry's first boot without some cajoling

### ISSUE THREAD

**Issue by kingdonb** [adfinis-sygroup/helm-charts#143]
**Affected chart**
sentry-apps

**Describe the bug**
ArgoCD does not finish progressing, fails to call "migrate" scripts on a brand new invocation.

**To Reproduce**

(start with a working installation of ArgoCD, the latest version is at 1.8.1)

1. (ensure there is enough CPU on the cluster, as the init containers have somewhat large requests compared to my staging cluster's node size, we are under-resourced...)
2. `helm fetch --untar adfinis/sentry-apps`; `cd sentry-apps`
3. copy `ingress-and-certificate.values.yaml` from the examples/ folder and customize with my own `ingress.hostname`, `tls[0].hosts[0]` to match, a randomly chosen postgresql password, and randomly chosen system.secretKey, save in `my.values.yaml`
4. `kubectl create ns sentry`; `kubens sentry`; `kubectl apply -f examples/sentry-issuer.yaml`
5. `helm upgrade --install sentry . --values my.values.yaml`
6. Find the newly created Application in the ArgoCD UI, press Sync, wait a while... it syncs the change to the cluster successfully, but the application's health check times out waiting for Progressing with the message "Sync failed"
7. Try syncing again (it doesn't help)

**Expected behavior**
Everything comes online, and the migrations are run by helm hooks

**Logs**
The "relay" pod does not become ready and is restarted a few times. Eventually some pods are left in crashloopbackoff. Inspection of the logs in sentry-web indicate that some migrations have not been run.

Carefully watching the progression of the rollout in argo and observing which pods are created, I note that the "hooks" init containers "initDb" and "initSnuba" as well as any others, never actually run; possibly there is some strangeness owing to ArgoCD's different handling than the upstream helm client. At a guess I would expect this to be a chicken-and-egg problem, (argo waits for healthy pods to run a post-install hook, or something like that? but the migration has not run before so pods are not healthy, so migrations will not run...)

```
$ kubectl get po -w
NAME                                                 READY   STATUS             RESTARTS   AGE
sentry-clickhouse-0                                  1/1     Running            0          17m
sentry-clickhouse-replica-0                          1/1     Running            0          17m
sentry-clickhouse-tabix-5564dc468-mszk7              1/1     Running            0          17m
sentry-cron-57c5d765f5-kbv6c                         1/1     Running            0          17m
sentry-ingest-consumer-6bc7cffcdd-m7mjx              1/1     Running            0          17m
sentry-kafka-0                                       1/1     Running            1          17m
sentry-nginx-79b8cf6989-68tk2                        1/1     Running            0          17m
sentry-post-process-forward-849fd6ddf7-gxskl         1/1     Running            0          17m
sentry-relay-6784f4b598-zmqmr                        0/1     CrashLoopBackOff   8          17m
sentry-sentry-postgresql-0                           1/1     Running            0          17m
sentry-sentry-redis-master-0                         1/1     Running            0          17m
sentry-sentry-redis-slave-0                          1/1     Running            0          17m
sentry-sessions-consumer-66c655cd-85s5x              0/1     CrashLoopBackOff   7          17m
sentry-snuba-api-fcb8c85fd-858rm                     1/1     Running            0          17m
sentry-snuba-consumer-746f86dc47-nkqkw               1/1     Running            2          17m
sentry-snuba-outcomes-consumer-666ff5d688-l7jp5      0/1     CrashLoopBackOff   7          17m
sentry-snuba-replacer-688769ff6c-mtdj6               0/1     CrashLoopBackOff   7          17m
sentry-snuba-transactions-consumer-57bf7bc58-6kwkx   1/1     Running            2          17m
sentry-web-5f447c4998-8wpq5                          1/1     Running            1          17m
sentry-worker-685fb4578f-lnlm5                       1/1     Running            0          17m
sentry-zookeeper-0                                   1/1     Running            0          17m
```

I did some digging to figure out, where missing tables should have been generated, it looks like `sentry upgrade` in sentry-web container is the softest-touch place to start. I try running it manually:

```
$ k exec -it sentry-web-5f447c4998-8wpq5 -- bash
root@sentry-web-5f447c4998-8wpq5:/# sentry upgrade
19:18:46 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
19:18:50 [INFO] sentry.plugins.github: apps-not-configured
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
...
  Applying social_auth.0001_initial... OK
19:21:15 [WARNING] sentry: Cannot initiate onboarding for organization (1) due to missing owners
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: Y
...
```

I create a user as it suggests, then the migrations have all finished successfully and relay becomes ready.

Now things are looking up, although `sessions-consumer`, `snuba-outcomes-consumer`, and `snuba-replacer` remain in crashloopbackoff. Their logs report about missing topics in kafka. (Result of another init hook that did not run yet.)

I manually trigger in the ArgoCD UI another Sync operation (or, if I manage to get this far before argocd has timed out and given up, it notices that relay is healthy and moves on with the rest of the helm stuff...) with relay in healthy status, Argo can successfully induce the necessary initDb and initSnuba hooks into action, clickhouseInit, userCreate, and any others.

This is enough to resolve remaining issues related to missing topics in kafka, more missing postgres tables, that were not created during my `sentry upgrade`. When the three containers left in CrashLoopBackOff get around to trying again, the Progressing status in ArgoCD changes to Healthy and all of the tabs in Sentry come online.

At this point it looks like things are honky-dory and I am able to log into Sentry, click around the various sections of the UI, and not getting any surprises like `Internal Server Error` – I have yet to add any apps to it or ingest any errors, (I may have certificate issues to resolve first) but all indications seem to point to "it's a basically usable sentry on-premise install now." 👍😎

**Affected version**
sentry-apps 0.3.6

**Values**
Just the example values as described in the steps to reproduce, above

**Environment**
```
$ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

**Additional context**
I added some noise to #12 before I realized it might not be related to my problem, just had a lot of keywords in common.

**Comment by kingdonb** [comment]
The short version is that `sentry-relay` does not become healthy without some migrations running first, and the migrations will not run until `sentry-relay` is healthy.

**Comment by kingdonb** [comment]
Yeah, confirmed: https://github.com/argoproj/argo-cd/issues/4288

ArgoCD PostSync is not a perfect substitute for Helm post-install. It's surprising that the `db-init` etc. hooks would eventually come around and work at all, when `sentry-relay` is becoming healthy but other pods are still not... maybe it's a trick.

**Comment by kingdonb** [comment]
To resolve the mystery...

`sessions-consumer`, `snuba-outcomes-consumer`, and `snuba-replacer` are all without liveness/readiness checks (they simply abort if they are not functioning), but `sentry-relay` has both liveness and readiness checks. So Argo does not consider `PostSync` for the app is ready until `sentry-relay` is ready as well, but the other three it does not care about.

Not sure how to resolve the issue, but that explains at least what is happening.

**Comment by kingdonb** [comment]
I think I'm going to contribute a blog post to resolve this. Coming soon.

**Comment by hairmare** [comment]
Quite a bit of this (ie. the lack of health checks on some resources) will have to be fixed in the upstream sentry charts. I can confirm that the initial deployment wasn't as easy as it should be due to the hooks issue you mention.

**Comment by kingdonb** [comment]
Yeah, it's not such a big deal to resolve it with a workaround I think, it would be nice to fix upstream (in argo) but for me, documenting the workaround seems like actually a better resolution because it will have no risk of unpredictable impacts on other projects that use Argo.

If I do not contribute the blog post by this week, then I will start to lose "points" in my gameified GTD system. I think it will land on a particular blog of mine, but not sure yet.

Here is at least a link to the commitment in the GTD system, though: http://kb.commits.to/review-sentry-helm-on-argocd-blog-post – please feel free to rattle my cage if this is still unresolved next week.

**Comment by kingdonb** [comment]
The blog post is out, I published it at the following URL, it details the easy workaround and the reason why it works:

https://blog.teamhephy.info/blog/posts/tutorials/argocd-sentry-apps.html

I plan to expand it to a more in-depth review of Sentry itself, (perhaps also going into some depth about using ArgoCD and the sentry-apps Helm chart that you've provided here.)

I am satisfied that the issue is resolved, maintainers please feel free to reopen if you feel a need for any further action here!
