### ISSUE TITLE
barman: Rewrite to Deployment

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/helm-charts#151]
**Is your feature request related to a problem? Please describe.**
The barman chart is currently deploying a StatefulSet, which makes handling the resize of a PVC pretty hard, because StatefulSet currently doesn't support resizing of a PVC created via the `volumeClaimTemplate` (see [kubernetes/kubernetes#68737](https://github.com/kubernetes/kubernetes/issues/68737) for context).

**Describe the solution you'd like**
Rewrite the barman chart to use a single replica Deployment.

**Describe alternatives you've considered**
Alternative is to jump through all the hoops required to resize a PVC created by a StatefulSet.

**Affected chart**
barman

**Comment by hairmare** [comment]
I guess we would want to support both for the time being or do we want to obsolete/deprecate using a StatefulSet asap?

**Comment by tongpu** [comment]
> I guess we would want to support both for the time being or do we want to obsolete/deprecate using a StatefulSet asap?

I believe it was a mistake to implement it that way to begin with, so I would immediately remove support, but if we find a simple way to support both for a while it would be okay for me too.

**Comment by sinicis** [comment]
issue is solved with #171 and was deployed to production two weeks ago.

**Comment by snailxr** [comment]
After update to deployment when `helm delete`  the PVC will be deleted... 
Any solutions to keep the PVC when run command  `helm delete`?

**Comment by tongpu** [comment]
> After rewrite to Deployment when `helm delete` the PVC will be deleted... Any solutions to keep the PVC when run command `helm delete`?

You could try if adding the annotation
```
helm.sh/resource-policy: "keep"
```
to the PVC keeps it from getting deleted.

**Comment by snailxr** [comment]
> ```
> helm.sh/resource-policy: "keep"
> ```

@tongpu Thank you! 
Seems only works when adding `"helm.sh/resource-policy": keep` in PVC template.
When I use `kubectl` to update the annotations directly it will not work

**Comment by tongpu** [comment]
@snailxr Could you please open a separate feature request for this.
