### ISSUE TITLE
customer-center: Implement Helm chart for customer center

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/helm-charts#176]
**Is your feature request related to a problem? Please describe.**
We need to build a Helm chart for deploying the [customer-center](https://github.com/adfinis-sygroup/customer-center) application.

**Describe the solution you'd like**
We want to deploy the customer-center to our Kubernetes infrastructure in the future. For that we need a Helm chart that manages the deployment of the application.

**Additional context**
The configuration might be very similar to Helm charts that we're already using like [timed](https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/timed). We're going to need a Deployment for the frontend image and another Deployment for the backend image and Ingress should be used to route HTTP request to either of them based on the [configuration used for local development](https://github.com/adfinis-sygroup/customer-center/blob/master/provisioning/nginx/nginx-dev.conf), e.g. `/api` and `/socket.io` need to be routed to the backend Deployment and everything else can be sent to the frontend Deployment.

Please check with @fkm-adfinis regarding what configuration is required for external services like LDAP, timed and mail to ensure that the customer-center application works correctly.

Additional services from [`docker-compose.yml`](https://github.com/adfinis-sygroup/customer-center/blob/master/docker-compose.yml) that should be present in the Helm chart are `redis` and `postgresql`. They can possibly be added as subcharts.

**Comment by eyenx** [comment]
#188
