### ISSUE TITLE
Helm Repo addition before Chart-Releaser Action

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/helm-charts#197]
**Is your feature request related to a problem? Please describe.**
We should think about managing repo needed for chart-releaser action somewhere else

https://github.com/adfinis-sygroup/helm-charts/pull/196#issue-595321086

**Describe the solution you'd like**
A separate file, containing the repo chart-relaser is looading before doing the release. Or somehow integrate it in the acation itself on upstream.

**Describe alternatives you've considered**
The one which is in use right now, just an additional step beforehand

**Affected chart**
All of em.

**Additional context**
failed action: https://github.com/adfinis-sygroup/helm-charts/runs/2137928051?check_suite_focus=true

**Comment by hairmare** [comment]
yupp... https://github.com/adfinis-sygroup/helm-charts/pull/196#issuecomment-802014595

> Maybe we could replace it with a script that grabs the repos from `./hack/chart-testing/ct.yaml`? We'd stilll need to manage both `./hack/chart-testing/ct.yaml` and `./hack/chart-testing/ct-install.yaml` but it would be a start.
