### ISSUE TITLE
[back8sup] chart installation on kind cluster not working

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/helm-charts#24]
The `local-path-provisioner` StorageClass used in kind clusters, is configured with `WaitForFirstConsumer` which means it waits for a Pod to actually bind the PVC.

This means we can't test the back8sup chart with kind-cluster action, as we have a only a Cronjob deployed which will only run a Pod at a given time (default at 1 AM).

How can we disable the helm-chart-linting on the kind cluster for `charts/back8sup`?

Thanks to @tongpu for bringing some light into this.

**Comment by hairmare** [comment]
I'm pretty sure that something is fishy with the PVC in #23 , the timed chart has bitnami/postgres as a dependency and is able to create a PVC and start up just fine.

**Comment by hairmare** [comment]
Maybe you can do a `kubectl create job --from=cronjob/<cronjob-name> <job-name>` in a test container to trigger provisioning (and also to make sure that we we install actually works).

**Comment by eyenx** [comment]
> Maybe you can do a `kubectl create job --from=cronjob/<cronjob-name> <job-name>` in a test container to trigger provisioning (and also to make sure that we we install actually works).

That sounds interesting. How would I achieve that? can I run an action in the workflow only for the `back8sup` chart?

**Comment by hairmare** [comment]
> That sounds interesting. How would I achieve that? can I run an action in the workflow only for the `back8sup` chart?

Maybe https://helm.sh/docs/helm/helm_test/ works for this case? I'm not sure if running an action in the workflow for just this case is sensible, better check if `helm test` can help of see if you can deactivate untestable parts in a `ci/*.yaml` file for your chart.

**Comment by hairmare** [comment]
If you can't get this to run using `helm test` you should consider adding `persistence.enabled` in `values.yaml` and using an `emptyDir` volume if it is false. 

You can then create `charts/back8sup/ci/default.yaml` containing some minimal yaml to set that to `false`. The flag should govern creating the PVC as well as the volume in the actual container.

This way we would at least be checking the CronJob for validity even though the PVC gets skipped.

**Comment by eyenx** [comment]
I've not had any time to look into helm test yet.

**Comment by hairmare** [comment]
> I've not had any time to look into helm test yet.

no worries

**Comment by eyenx** [comment]
fixed in #23 thanks @hairmare
