### ISSUE TITLE
Automate PR creation with @adfinisbot

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/helm-charts#359]
**Is your feature request related to a problem? Please describe.**
We see we are lacking behind lots of version in our Charts if we are not constantly updating them.

**Describe the solution you'd like**
I would love some kind of automation for PR Creation like @dependabot already does for our GitHub Actions but for updating the targetRevision we are using in our apps-of-apps charts.

**Describe alternatives you've considered**
Creating issues with a script, I'm already using.

**Affected chart**
All apps-of-apps charts targeting a Chart Revision over the `values.yaml` 

**Additional context**
The bot /script needs to make sure the targetRevisioon is updated inside the values.yaml, also, as long as we aren't automating the chart version bumping (#218) , it has to do that too. In the end, `pre-commit run -a` needs to be run to update all `README.md`s.

See PR  #357 as example update of a targetRevision inside a app-of-apps chart
See Issue

**Comment by hairmare** [comment]
Duplicates #341 218

**Comment by Akinboss1** [comment]
Hello

**Comment by eyenx** [comment]
Hi @kebarb any update on this issue?

**Comment by hairmare** [comment]
Closing because it's a dupe, if anything is missing from #218 feel free to add it there.
