### ISSUE TITLE
argoconfig: allow configuring multiple clusters

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/helm-charts#37]
Like with the apps after #34 we want to be able to configure multiple clusters with the argoconfig chart.

**Comment by tongpu** [comment]
How would we manage a phased rollout of a specific set of apps (e.g. infra-apps) to different clusters with this approach? Multiple instances of the argoconfig chart with different versions or is there some mechanism in Argo CD that would allow us to manage that?

**Comment by hairmare** [comment]
I was thinking that a "prod" argocd could deploy an "infra-apps" onto a "test" cluster using a different version of the "infra-apps" chart.

My use case here is about being able to deploy to multiple clusters (ie. for a `<customer>-apps` stack chart).
