### ISSUE TITLE
[Security] Workflow test.yaml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by Freakston** [adfinis-sygroup/helm-charts#494]
The workflow test.yaml is referencing action pre-commit/action using references v2.0.3. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by hairmare** [comment]
Hi @Freakston 

Thank you for your report. We take issues like this seriously. I'm not sure i understand why you feel we are vulnerable.

The commit you reference (https://github.com/pre-commit/action/commit/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) is from 5. May 2020. This was released with v2.0.1. The version we currently use (v2.0.3) was released on 21. April 2021, which is later that the fix you reference is applied.

I had a look at your profile and am finding it hard to believe that you verified the vulnerability on all the >400  different repos you've been reporting similar vulnerablities.

Could you please elaborate on the issue? 

You can find my direct contact in my profile if there is info you can't disclose on this public message.

**Comment by eyenx** [comment]
I reported this fellow to GitHub for SPAM.

**Comment by Freakston** [comment]
@hairmare sorry about this issue report. It was generated by an automated tool. Thanks for the information.

**Comment by hairmare** [comment]
@Freakston I would suggest that you make said tool opt-in, otherwise your actions might be viewed as spammy by some.
