### ISSUE TITLE
barman: When uninstall barman helm chart the pvc should keep but not be deleted

### ISSUE THREAD

**Issue by snailxr** [adfinis-sygroup/helm-charts#644]
**Is your feature request related to a problem? Please describe.**
After barman is rewritten from statefulset to deployment(#151) when uninstalling barman the PVC will be deleted.
**Describe the solution you'd like**
When uninstalling barman the PVC should keep there.
Update the PVC template add config, if add annotation `"helm.sh/resource-policy": keep` .
**Describe alternatives you've considered**
Rollback to using statefulset, lost backup data is a more serious problem.

**Comment by tongpu** [comment]
@luk43 This could be a task that Lukas could work on. I would suggest that we configure the default to be to not add the annotation, but add a `persistence.data.keepOnUninstall` parameter that allows one to add the annotation.

**Comment by hairmare** [comment]
I'm adding the possibility to specify any annotation on the underlying PVCs in #691 

Setting such annotations will work fine if you deploy the chart using Helm. In cases where `helm template` based tools are used (ie. Argo CD) the annotation won't work.

In those case we recommend setting up a dedicated StorageClass  with `reclaimPolicy: Retain` to ensure that all PVs get created with `persistentVolumeReclaimPolicy: Retain` from the get go. In addition to working with tols like Argo CD, this will not only protect the PVs from a `helm delete` but also `kubectl delete`. More details about the reclaim policy are [in the Kubernetes docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy).
